// <auto-generated />
using System;
using EarlyYearsFoundationRecovery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EarlyYearsFoundationRecovery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613173952_AddClosedReasonFieldsToUsers")]
    partial class AddClosedReasonFieldsToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Assessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<float?>("Score")
                        .HasColumnType("real")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("TrainingModule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("training_module");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_assessments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_assessments_user_id");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long?>("VisitId")
                        .HasColumnType("bigint")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_events_user_id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_events_visit_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.MailEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Callback")
                        .HasColumnType("jsonb")
                        .HasColumnName("callback");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Personalisation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("personalisation");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mail_events");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mail_events_user_id");

                    b.ToTable("mail_events", (string)null);
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Note", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TrainingModule")
                        .HasColumnType("text")
                        .HasColumnName("training_module");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notes_user_id");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Response", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers");

                    b.Property<long?>("AssessmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assessment_id");

                    b.Property<bool?>("Correct")
                        .HasColumnType("boolean")
                        .HasColumnName("correct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("QuestionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_name");

                    b.Property<string>("QuestionType")
                        .HasColumnType("text")
                        .HasColumnName("question_type");

                    b.Property<string>("TextInput")
                        .HasColumnType("text")
                        .HasColumnName("text_input");

                    b.Property<string>("TrainingModule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("training_module");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long?>("VisitId")
                        .HasColumnType("bigint")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_responses");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("ix_responses_assessment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_responses_user_id");

                    b.ToTable("responses", (string)null);
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedReason")
                        .HasColumnType("text")
                        .HasColumnName("closed_reason");

                    b.Property<string>("ClosedReasonCustom")
                        .HasColumnType("text")
                        .HasColumnName("closed_reason_custom");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EarlyYearsExperience")
                        .HasColumnType("text")
                        .HasColumnName("early_years_experience");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("GovOneId")
                        .HasColumnType("text")
                        .HasColumnName("gov_one_id");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LocalAuthority")
                        .HasColumnType("text")
                        .HasColumnName("local_authority");

                    b.Property<bool>("RegistrationComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("registration_complete");

                    b.Property<bool?>("ResearchParticipant")
                        .HasColumnType("boolean")
                        .HasColumnName("research_participant");

                    b.Property<string>("RoleType")
                        .HasColumnType("text")
                        .HasColumnName("role_type");

                    b.Property<string>("RoleTypeOther")
                        .HasColumnType("text")
                        .HasColumnName("role_type_other");

                    b.Property<string>("SettingType")
                        .HasColumnType("text")
                        .HasColumnName("setting_type");

                    b.Property<string>("SettingTypeOther")
                        .HasColumnType("text")
                        .HasColumnName("setting_type_other");

                    b.Property<DateTime?>("TermsAndConditionsAgreedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_and_conditions_agreed_at");

                    b.Property<bool>("TrainingEmails")
                        .HasColumnType("boolean")
                        .HasColumnName("training_emails");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GovOneId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_gov_one_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.UserModuleProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastPage")
                        .HasColumnType("text")
                        .HasColumnName("last_page");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module_name");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("VisitedPages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("visited_pages");

                    b.HasKey("Id")
                        .HasName("pk_user_module_progress");

                    b.HasIndex("UserId", "ModuleName")
                        .IsUnique()
                        .HasDatabaseName("ix_user_module_progress_user_id_module_name");

                    b.ToTable("user_module_progress", (string)null);
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Visit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LandingPage")
                        .HasColumnType("text")
                        .HasColumnName("landing_page");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("VisitToken")
                        .HasColumnType("text")
                        .HasColumnName("visit_token");

                    b.Property<string>("VisitorToken")
                        .HasColumnType("text")
                        .HasColumnName("visitor_token");

                    b.HasKey("Id")
                        .HasName("pk_visits");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_visits_user_id");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("EarlyYearsFoundationRecovery.Domain.Entities.User", "User")
                        .WithMany("Assessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Event", b =>
                {
                    b.HasOne("EarlyYearsFoundationRecovery.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_events_users_user_id");

                    b.HasOne("EarlyYearsFoundationRecovery.Domain.Entities.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .HasConstraintName("fk_events_visits_visit_id");

                    b.Navigation("User");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.MailEvent", b =>
                {
                    b.HasOne("EarlyYearsFoundationRecovery.Domain.Entities.User", "User")
                        .WithMany("MailEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mail_events_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Note", b =>
                {
                    b.HasOne("EarlyYearsFoundationRecovery.Domain.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Response", b =>
                {
                    b.HasOne("EarlyYearsFoundationRecovery.Domain.Entities.Assessment", "Assessment")
                        .WithMany("Responses")
                        .HasForeignKey("AssessmentId")
                        .HasConstraintName("fk_responses_assessments_assessment_id");

                    b.HasOne("EarlyYearsFoundationRecovery.Domain.Entities.User", "User")
                        .WithMany("Responses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_responses_users_user_id");

                    b.Navigation("Assessment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.UserModuleProgress", b =>
                {
                    b.HasOne("EarlyYearsFoundationRecovery.Domain.Entities.User", "User")
                        .WithMany("ModuleProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_module_progress_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Visit", b =>
                {
                    b.HasOne("EarlyYearsFoundationRecovery.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_visits_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("EarlyYearsFoundationRecovery.Domain.Entities.User", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("MailEvents");

                    b.Navigation("ModuleProgress");

                    b.Navigation("Notes");

                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
